#!/bin/bash

MYBASE=/home/pueo
MYSTARTUP=/home/pueo/pueo-scripts/taylor/ppy_startup.py
export PYTHONSTARTUP=$MYSTARTUP
export PYTHONPATH=$MYBASE/pueo-python:$MYBASE/pueo-utils/HskSerial:$PYTHONPATH

python3 "$@"

